version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/python:3.9.6

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: |
          docker build -t quiz-app:latest .
          docker tag quiz-app:latest $DOCKER_USERNAME/quiz-app:latest
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/quiz-app:latest


workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
